Tried to fix problem caused by not using the old field Lookup() methods.  These methods would generated ObservedField events.  I have to replace them with something.  Changed things so that the Depository does not throw away the field information it reads from the fields.txt file for fields that do not have classes that appear in the sites.txt file.  Changed the field access methods to call Phantom.ofClass() method for classes that declare fields but that are not instrumented.  This two cahnges cause the field-declaration elements to appear in the flashlight data file that used to be generated using ObservedField events.
The original problem was observed with the planet baron server.  This works now.  But I still have some problems with using Vuze/Azureus.  Not sure if I am seeing the same or a different problem.  Got 

(SureLogic #116) General failure during data preparation of the raw data file com.aelitis.azureus.ui.swt.Initializer-2009.05.14-at-15.13.20.182.fl.
java.lang.IllegalStateException: (SureLogic #12) The statement:
ALTER TABLE "FLASHLIGHT"."ACCESS" ADD CONSTRAINT "ACCESS_FIELD_FK" FOREIGN KEY ("FIELD") REFERENCES "FLASHLIGHT"."FIELD" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION
in the script bundleresource://200/com/surelogic/flashlight/schema/add_constraints.sql has failed to execute properly.
  Plug-in Vendor: SureLogic, Inc.
  Plug-in Name: SureLogic Common Code for Eclipse
  Version: 2.2.1.qualifier
  Plug-in ID: com.surelogic.common.eclipse
  Plug-in Serviceability Code: (SureLogic #116)

When trying to prep a 4GB data file.  This occurred when prepping was almost finished (after 1+ hours).


git-svn-id: https://fluid.surelogic.com/svn/eng/trunk/flashlight-client-eclipse@12310 d02ae147-ee12-4a35-9452-91c89e8b2592